### ISSUE TITLE
Issue while saving "integrationConfiguration" object in Pimcore

### ISSUE THREAD

**Issue by diamondzacx** [DivanteLtd/pimcore-magento2-bridge#1]
Getting following error while saving object of "integrationConfiguration" class.

Timestamp: Fri Dec 28 2018 15:18:53 GMT+0530 (IST)
Status: 500 | Internal Server Error
URL: /admin/object-mapper/get-columns-product
Method: GET
Message: Attempted to load class "FromColumn" from namespace "Divante\MagentoIntegrationBundle\Model\Mapping".
Did you forget a "use" statement for another namespace?
 
Need to figure it out for setup completion.

**Comment by mbolka** [comment]
@diamondzacx This issue has been solved. Thx
