### ISSUE TITLE
API: No configuration was found for this object.

### ISSUE THREAD

**Issue by bartoll** [DivanteLtd/pimcore-magento2-bridge#10]
{
"name": "pimcore/demo-ecommerce",
"type": "project",
"description": "E-Commerce Demo Application for Pimcore 5",
"license": "GPL-3.0-or-later",
"config": {
"optimize-autoloader": true,
"sort-packages": true
},
"require": {
"php": ">=7.1",
"divante-ltd/pimcore-magento2-bridge": "^1.0",
"pimcore/customer-management-framework-bundle": "^1.9",
"pimcore/pimcore": "~5.7.0",
"pimcore/server-side-matomo-tracking": "^0.1",
"pimcore/web2print-tools-bundle": "^2.4",
"wikimedia/composer-merge-plugin": "^1.4"
},
}

I have a problem with webservice API from Pimcore side.

I have object of configuration and properly filled in all necessary fields as described on video from YT:

![image](https://user-images.githubusercontent.com/1619173/56206172-05a52200-604c-11e9-9b18-b022b9a2646b.png)

Unfortunately when I save my new category object and run CLI command on magento side, the command edns with no errors but nothing appears in magento's panel. I've discovered that problem is in pimcore and magento try to get object data of category with no success. In Pimcore there is some error in application log like this:
- No configuration was found for this object
- Requested object with id 12477 does not exist

![image](https://user-images.githubusercontent.com/1619173/56206413-a1cf2900-604c-11e9-983e-c0c7075c42ce.png)

When I checked this object exists in Pimcore and are properly sent to magento category queue.

Could you help me solving this problem?

**Comment by PandaCrafter1** [comment]
I have the same issue, this is my error message

![image](https://user-images.githubusercontent.com/5909098/56848118-33f4ee00-68e5-11e9-9b27-3dd46ffa3f72.png)

**Comment by PandaCrafter1** [comment]
@mbolka

**Comment by mbolka** [comment]
@bartoll Could you retest the newest version - 1.1.0  to verify if the problem still occurs?
