### ISSUE TITLE
Bundle "DivanteMagentoIntegrationBundle" does not exist or it is not enabled. 

### ISSUE THREAD

**Issue by onlinemusketeers** [DivanteLtd/pimcore-magento2-bridge#102]
Hi! After a clean install of Pimcore and following the steps for installation I come to this command with an error:

bin/console pimcore:bundle:install DivanteMagentoIntegrationBundle

In Kernel.php line 231:
                                                                                                                                                                            
  Bundle "DivanteMagentoIntegrationBundle" does not exist or it is not enabled. Maybe you forgot to add it in the "registerBundles()" method of your "AppKernel.php" file?  

What could be wrong here?

**Comment by kubaplas** [comment]
@onlinemusketeers did you enable the the bundle?
`bin/console pimcore:bundle:enable DivanteMagentoIntegrationBundle`

**Comment by onlinemusketeers** [comment]
Thank you for your reply. I am going to try that.  What do you recommend in terms of the initial installation of Pimcore? Is that skeleton or with demo data?

**Comment by onlinemusketeers** [comment]
Looks like everything works fine now. :)
