### ISSUE TITLE
Does not work with composer 2

### ISSUE THREAD

**Issue by jdigiorgio** [DivanteLtd/pimcore-magento2-bridge#105]
Installing using composer 2 causes a lot of errors of the type 'Class ... located in ... does not comply with psr-4 autoloading standard. Skipping.' After that process completes the bundle does not appear at all in pimcore:bundle:list and it cannot be enabled or installed. Downgrading to composer 1 works.

**Comment by mbolka** [comment]
Thank you for your ticket. We have updated develop-v2 with changes to fully comply with PSR-4. It should be working now.
