### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by p380** [DivanteLtd/pimcore-magento2-bridge#106]
when I want to install the module it returns an error
Method "Divante\MagentoIntegrationBundle\Application\Validator\Rules\Category\CategoryParentsMustBePublished::getPriority()" should return a string (got "integer").

I have a clean instalation PIMCore.
which vendor is missing? 

regards

**Comment by mbolka** [comment]
Thank you! We have fixed that on develop-v2 branch.
