### ISSUE TITLE
Install via composer

### ISSUE THREAD

**Issue by p380** [DivanteLtd/pimcore-magento2-bridge#108]
how to install composer version for branch 'develop-v2' on Pimcore clean installation?

**Comment by prugala** [comment]
`composer require divante-ltd/pimcore-magento2-bridgedev-develop-v2`

**Comment by jdigiorgio** [comment]
Does the develop-v2 version work the master version of magento2-pimcore-bridge?

**Comment by prugala** [comment]
I don't know, @mbolka maybe you can answer :)

**Comment by p380** [comment]
I know it works with development version of the Magento module.

**Comment by p380** [comment]
> `composer require divante-ltd/pimcore-magento2-bridgedev-develop-v2`

minor error, the correct command is:
composer require divante-ltd/pimcore-magento2-bridge:dev-develop-v2

**Comment by p380** [comment]
issue closed
