### ISSUE TITLE
Exception during instalation process

### ISSUE THREAD

**Issue by bartoll** [DivanteLtd/pimcore-magento2-bridge#11]
{
  "name": "pimcore/demo-ecommerce",
  "type": "project",
  "description": "E-Commerce Demo Application for Pimcore 5",
  "license": "GPL-3.0-or-later",
  "config": {
    "optimize-autoloader": true,
    "sort-packages": true
  },
  "require": {
    "php": ">=7.1",
    "divante-ltd/pimcore-magento2-bridge": "^1.0",
    "pimcore/customer-management-framework-bundle": "^1.9",
    "pimcore/pimcore": "~5.7.0",
    "pimcore/server-side-matomo-tracking": "^0.1",
    "pimcore/web2print-tools-bundle": "^2.4",
    "wikimedia/composer-merge-plugin": "^1.4"
  },
}

I was installing your module according to description of installation process.
There is point:

> Install Bundle by running bin/console pimcore:bundle:install DivanteMagentoIntegrationBundle

After running this command I have got an exception like below:

> vagrant@vps617093:/var/www/vagrant/pimcore.project$ bin/console pimcore:bundle:install DivanteMagentoIntegrationBundle
> Installing bundle DivanteMagentoIntegrationBundle
> 
> Migrating up to 00000001 from 0
> 
>   ++ migrating 00000001
> 
> 11:04:36 ERROR     [pimcore] Exception: There is no class with the name: integrationConfiguration in /var/www/vagrant/pimcore.project/vendor/pimcore/pimcore/models/DataObject/ClassDefinition.php:232
> Stack trace:
> #0 /var/www/vagrant/pimcore.project/vendor/divanteltd/pimcoredevkit/src/PimcoreDevkitBundle/Service/InstallerService.php(169): Pimcore\Model\DataObject\ClassDefinition::getByName('integrationConf...')
> #1 /var/www/vagrant/pimcore.project/vendor/divanteltd/pimcoredevkit/src/PimcoreDevkitBundle/Service/InstallerService.php(157): PimcoreDevkitBundle\Service\InstallerService->createClassDefinitionFromString('integrationConf...', '{\n    "id": "4"...')
> #2 /var/www/vagrant/pimcore.project/vendor/divante-ltd/pimcore-magento2-bridge/src/Divante/MagentoIntegrationBundle/Migrations/Installer.php(72): PimcoreDevkitBundle\Service\InstallerService->createClassDefinition('integrationConf...', '/var/www/vagran...')
> #3 /var/www/vagrant/pimcore.project/vendor/pimcore/pimcore/lib/Migrations/Migration/InstallMigration.php(44): Divante\MagentoIntegrationBundle\Migrations\Installer->migrateInstall(Object(ProxyManagerGeneratedProxy\__PM__\Doctrine\DBAL\Schema\Schema\Generated93cb4e52be36d1a0ab1c551957e06e24), Object(Pimcore\Migrations\InstallVersion))
> #4 /var/www/vagrant/pimcore.project/vendor/pimcore/pimcore/lib/Migrations/Version.php(312): Pimcore\Migrations\Migration\InstallMigration->up(Object(ProxyManagerGeneratedProxy\__PM__\Doctrine\DBAL\Schema\Schema\Generated93cb4e52be36d1a0ab1c551957e06e24))
> #5 /var/www/vagrant/pimcore.project/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Migration.php(172): Pimcore\Migrations\Version->execute('up', false, false)
> #6 /var/www/vagrant/pimcore.project/vendor/pimcore/pimcore/lib/Extension/Bundle/Installer/MigrationInstaller.php(351): Doctrine\DBAL\Migrations\Migration->migrate('00000001', false)
> #7 /var/www/vagrant/pimcore.project/vendor/pimcore/pimcore/lib/Extension/Bundle/Installer/MigrationInstaller.php(145): Pimcore\Extension\Bundle\Installer\MigrationInstaller->executeInstallMigration(true)
> #8 /var/www/vagrant/pimcore.project/vendor/pimcore/pimcore/lib/Extension/Bundle/PimcoreBundleManager.php(484): Pimcore\Extension\Bundle\Installer\MigrationInstaller->install()
> #9 /var/www/vagrant/pimcore.project/vendor/pimcore/pimcore/bundles/CoreBundle/Command/Bundle/InstallCommand.php(45): Pimcore\Extension\Bundle\PimcoreBundleManager->install(Object(Divante\MagentoIntegrationBundle\DivanteMagentoIntegrationBundle))
> #10 /var/www/vagrant/pimcore.project/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(255): Pimcore\Bundle\CoreBundle\Command\Bundle\InstallCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #11 /var/www/vagrant/pimcore.project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(978): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #12 /var/www/vagrant/pimcore.project/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(86): Symfony\Component\Console\Application->doRunCommand(Object(Pimcore\Bundle\CoreBundle\Command\Bundle\InstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #13 /var/www/vagrant/pimcore.project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(255): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Pimcore\Bundle\CoreBundle\Command\Bundle\InstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #14 /var/www/vagrant/pimcore.project/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(74): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #15 /var/www/vagrant/pimcore.project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(148): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #16 /var/www/vagrant/pimcore.project/bin/console(26): Symfony\Component\Console\Application->run()
> #17 {main}
> Migration 00000001 was executed but did not result in any SQL statements.

Despite this exception, the module was installed and I was able to configure it in Pimcore.

**Comment by prugala** [comment]
Its output from logger. Pimcore throws an exception when Class definition dosent exists, then catches it.
https://github.com/pimcore/pimcore/blob/master/models/DataObject/ClassDefinition.php#L224

**Comment by bartoll** [comment]
Is it acceptable situation in Pimcore 5.4 with coreshop ecommerce bundle?

**Comment by bartoll** [comment]
TODO:
- check if problem still exists after executing
> bin/console pimcore:deployment:classes-rebuild
> bin/console cache:clear

**Comment by mbolka** [comment]
@bartoll Yes it is an acceptable situation
