### ISSUE TITLE
Attempted to load class "IntegrationConfiguration" from namespace "Pimcore\Model\DataObject".

### ISSUE THREAD

**Issue by The-Creeps** [DivanteLtd/pimcore-magento2-bridge#111]
Hello everyone,

Environement : Ubuntu 18.04, PHP 7.2, Fresh Pimcore 6.8.11 "squeleton" tested with "demo" version too.
plugin version : dev-develop-v2

Impossible to procced at the plugin install. 
I have the same problem on current preprod pimcore 6.5.3 server.

```
Attempted to load class "IntegrationConfiguration" from namespace "Pimcore\Model\DataObject". 
Did you forget a "use" statement for "Divante\MagentoIntegrationBundle\Domain\DataObject\IntegrationConfiguration"?

Server threw exception - could not perform action. Please reload the admin interface and try again.
```

see file attachement
![Capture](https://user-images.githubusercontent.com/8341054/113319661-f9d2c900-9311-11eb-97ba-c4a6c79e3a45.JPG)

Have you any idea to fix this ?
Thank's for your help.

**Comment by The-Creeps** [comment]
Resolved

**Comment by msnyder-wayside** [comment]
> Resolved

I know it's two years later, but do you recall what you did to resolve this?
