### ISSUE TITLE
Installation of coreshop/resource-bundle and symfony 4.3.1 fails

### ISSUE THREAD

**Issue by giorgiolami** [DivanteLtd/pimcore-magento2-bridge#13]
Trying to install coreshop/resource-bundle I get a fail message:

"Installation request for symfony/http-foundation (locked at v.4.3.1) -> satisfiable by symfony/http-foundation[v.4.3.1]

Any tip?

**Comment by mbolka** [comment]
Hi
Thank you for your report. Coreshop/resource-bundle is not our package. Please head to https://github.com/coreshop/CoreShop/issues in order to report it.
