### ISSUE TITLE
Integrated category & Integrated product Class are not created.

### ISSUE THREAD

**Issue by nishantjariwala** [DivanteLtd/pimcore-magento2-bridge#14]
Hello,
I've installed pimcore-magento2-bridge extension but it doesn't create IntegratedCategory & IntegratedProduct class after installation.
Also, I got below error after execution of **bin/console pimcore:bundle:install DivanteMagentoIntegrationBundle** with pimcore 5.8 version.

Stack trace:
>#0 /var/www/html/pim-ecom/vendor/divanteltd/pimcoredevkit/src/PimcoreDevkitBundle/Service/InstallerService.php(169): Pimcore\Model\DataObject\ClassDefinition::getByName('integrationConf...')
>#1 /var/www/html/pim-ecom/vendor/divanteltd/pimcoredevkit/src/PimcoreDevkitBundle/Service/InstallerService.php(157): PimcoreDevkitBundle\Service\InstallerService->createClassDefinitionFromString('integrationConf...', '{\n    "id": "4"...')
>#2 /var/www/html/pim-ecom/vendor/divante-ltd/pimcore-magento2-bridge/src/Divante/MagentoIntegrationBundle/Migrations/Installer.php(72): PimcoreDevkitBundle\Service\InstallerService->createClassDefinition('integrationConf...', '/var/www/html/p...')
>#3 /var/www/html/pim-ecom/vendor/pimcore/pimcore/lib/Migrations/Migration/InstallMigration.php(44): Divante\MagentoIntegrationBundle\Migrations\Installer->migrateInstall(Object(ProxyManagerGeneratedProxy\__PM__\Doctrine\DBAL\Schema\Schema\Generateda7193b54919e65c954d994217ebb5fab), Object(Pimcore\Migrations\InstallVersion))
>#4 /var/www/html/pim-ecom/vendor/pimcore/pimcore/lib/Migrations/Version.php(312): Pimcore\Migrations\Migration\InstallMigration->up(Object(ProxyManagerGeneratedProxy\__PM__\Doctrine\DBAL\Schema\Schema\Generateda7193b54919e65c954d994217ebb5fab))
>#5 /var/www/html/pim-ecom/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Migration.php(172): Pimcore\Migrations\Version->execute('up', false, false)
>#6 /var/www/html/pim-ecom/vendor/pimcore/pimcore/lib/Extension/Bundle/Installer/MigrationInstaller.php(351): Doctrine\DBAL\Migrations\Migration->migrate('00000001', false)
>#7 /var/www/html/pim-ecom/vendor/pimcore/pimcore/lib/Extension/Bundle/Installer/MigrationInstaller.php(145): Pimcore\Extension\Bundle\Installer\MigrationInstaller->executeInstallMigration(true)
>#8 /var/www/html/pim-ecom/vendor/pimcore/pimcore/lib/Extension/Bundle/PimcoreBundleManager.php(484): Pimcore\Extension\Bundle\Installer\MigrationInstaller->install()
>#9 /var/www/html/pim-ecom/vendor/pimcore/pimcore/bundles/CoreBundle/Command/Bundle/InstallCommand.php(45): Pimcore\Extension\Bundle\PimcoreBundleManager->install(Object(Divante\MagentoIntegrationBundle\DivanteMagentoIntegrationBundle))
>#10 /var/www/html/pim-ecom/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(255): Pimcore\Bundle\CoreBundle\Command\Bundle\InstallCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
>#11 /var/www/html/pim-ecom/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(987): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
>#12 /var/www/html/pim-ecom/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(86): Symfony\Component\Console\Application->doRunCommand(Object(Pimcore\Bundle\CoreBundle\Command\Bundle\InstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
>#13 /var/www/html/pim-ecom/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(255): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Pimcore\Bundle\CoreBundle\Command\Bundle\InstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
>#14 /var/www/html/pim-ecom/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(74): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
>#15 /var/www/html/pim-ecom/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(148): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
>#16 /var/www/html/pim-ecom/bin/console(26): Symfony\Component\Console\Application->run()
>#17 {main}
>Migration 00000001 was executed but did not result in any SQL statements.
>
>  ++ migrated (1.14s)
>
>  ------------------------
>
>  ++ finished in 1.14s
>  ++ 1 migrations executed
>  ++ 0 sql queries

Can you please help me to fix this thing?

Thanks

**Comment by mbolka** [comment]
Hi!
Thank you for your report. Can you verify if in the newest version 1.1.0 problem still occurs?
It supports Pimcore 6.x now.

**Comment by mbolka** [comment]
@nishantjariwala Can you confirm if the problem still occurs?

**Comment by mbolka** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the [1.2.0](https://github.com/DivanteLtd/pimcore-magento2-bridge/tree/1.2.0) and then please [ireport issue](https://github.com/DivanteLtd/pimcore-magento2-bridge/issues/new). You can also contribute directly by providing a patch.
Thank you!
