### ISSUE TITLE
Fatal error while installation

### ISSUE THREAD

**Issue by SergeyGauert** [DivanteLtd/pimcore-magento2-bridge#18]
getting error after bin/console pimcore:bundle:enable DivanteMagentoIntegrationBundle
(pimcore 6.0.2)
 
> Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\RuntimeException: Cannot autowire service "Divante\MagentoIntegrationBundle\Service\Product\ProductStatusService": argument "$mapper" of method "Divante\MagentoIntegrationBundle\Service\AbstractObjectService::__construct()" references interface "Divante\MagentoIntegrationBundle\Interfaces\MapperInterface" but no such service exists. Did you create a class that implements this interface? in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/DefinitionErrorExceptionPass.php:54
> Stack trace:
> #0 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(82): Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass->processValue(Object(Symfony\Component\DependencyInjection\Definition), true)
> #1 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/DefinitionErrorExceptionPass.php(32): Symfony\Component\DependencyInje in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/DefinitionErrorExceptionPass.php on line 54

**Comment by prugala** [comment]
Hello

Please try to enable `DivanteObjectMapperBundle` bundle before with commend (or in Pimcore panel Tools > Bundles):
`bin/console pimcore:bundle:enable DivanteObjectMapperBundle`

**Comment by SergeyGauert** [comment]
> Hello
> 
> Please try to enable `DivanteObjectMapperBundle` bundle before with commend (or in Pimcore panel Tools > Bundles):
> `bin/console pimcore:bundle:enable DivanteObjectMapperBundle`
hello, thank you for help!
it works but now im getting this
"Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: The service "coreshop.command.create_database_tables" has a dependency on a non-existent parameter "coreshop.resources". in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php:100
Stack trace:
#0 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/EnvPlaceholderParameterBag.php(67): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get('coreshop.resour...')
#1 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(216): Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag->get('coreshop.resour...')
#2 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(187): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->resolveString('%coreshop.resou...', Array)
#3 /var/www/html/v in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php on line 100"

**Comment by SergeyGauert** [comment]
what should i do to fix such errors so i could stop reinstall pimcore over and over?

**Comment by prugala** [comment]
I got the same error. I will investigate and fix it tomorrow. At the moment please edit your `var/config/extensions.php` file and sort bundles in this order. 

```php
        "CoreShop\\Bundle\\ResourceBundle\\CoreShopResourceBundle" => TRUE,
        "CoreShop\\Bundle\\PimcoreBundle\\CoreShopPimcoreBundle" => TRUE,
        "PimcoreDevkitBundle\\PimcoreDevkitBundle" => TRUE,
        "Divante\\ObjectMapperBundle\\DivanteObjectMapperBundle" => TRUE,
        "Divante\\MagentoIntegrationBundle\\DivanteMagentoIntegrationBundle" => TRUE
```

Clear cache with `bin/console c:c` and site should works.

**Comment by BPWBeck** [comment]
Hey, did you get any results yesterday?

**Comment by prugala** [comment]
Hi, no

In the instalation instruction we have information about bundles which user should enable. One thing is change order in instruction second (better):
In Installer class add checking that other bundles are enabled if not turn them on
https://github.com/DivanteLtd/pimcore-magento2-bridge/blob/master/src/Divante/MagentoIntegrationBundle/Migrations/Installer.php

We are open on Pull Requests :)

https://github.com/DivanteLtd/pimcore-magento2-bridge#installinggetting-started

**Comment by SergeyGauert** [comment]
so right now i cant do anything with coreshop.resources error?

**Comment by prugala** [comment]
You can edit your extensions file as I wrote above:
https://github.com/DivanteLtd/pimcore-magento2-bridge/issues/18#issuecomment-511229574

In new projects bundles should be installed in this order:
1. `bin/console pimcore:bundle:enable CoreShopResourceBundle`
2. `bin/console pimcore:bundle:enable DivanteObjectMapperBundle`
3. `bin/console pimcore:bundle:enable DivanteMagentoIntegrationBundle`

**Comment by SergeyGauert** [comment]
oh, my bad. thank you!

**Comment by SergeyGauert** [comment]
so i try'd your advise above, same error after cleaning cache ((
![image](https://user-images.githubusercontent.com/38656588/61392664-fee6af00-a8c7-11e9-9446-a6997effe583.png)
bin/console c:c
Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: The service "coreshop.command.create_database_tables" has a dependency on a non-existent parameter "coreshop.resources". in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php:100
Stack trace:
#0 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/EnvPlaceholderParameterBag.php(67): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get('coreshop.resour...')
#1 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(216): Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag->get('coreshop.resour...')
#2 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(187): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->resolveString('%coreshop.resou...', Array)
#3 /var/www/html/v in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php on line 100

**Comment by SergeyGauert** [comment]
funny: i can exec

**Comment by SergeyGauert** [comment]
funny: i can exec
bin/console pimcore:bundle:enable DivanteMagentoIntegrationBundle
then 
bin/console pimcore:bundle:enable DivanteObjectMapperBundle
but after this everything goes black =(
bin/console pimcore:bundle:enable CoreShopResourceBundle

**Comment by mbolka** [comment]
@SergeyGauert Because many users have encountered issues with CoreShopResourceBundle we have decided to remove this dependency. Could you confirm if your problem still occurs?

**Comment by mbolka** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the [1.2.0](https://github.com/DivanteLtd/pimcore-magento2-bridge/tree/1.2.0) and then please [ireport issue](https://github.com/DivanteLtd/pimcore-magento2-bridge/issues/new). You can also contribute directly by providing a patch.
Thank you!
