### ISSUE TITLE
Install issue on pimcore 6.0 clean install, how to fix?

### ISSUE THREAD

**Issue by supportnubix** [DivanteLtd/pimcore-magento2-bridge#19]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for divante-ltd/pimcore-magento2-bridge ^1.1 -> satisfiable by divante-ltd/pimcore-magento2-bridge[1.1.1].
    - divante-ltd/pimcore-magento2-bridge 1.1.1 requires coreshop/resource-bundle dev-master -> satisfiable by coreshop/resource-bundle[dev-master] but these conflict with your requirements or minimum-stability.

**Comment by prugala** [comment]
Hello

You need to add to your composer.json:
```
"minimum-stability": "dev",
"prefer-stable": true
```

**Comment by supportnubix** [comment]
Thanks, that works. but the next command to install fails. 

php bin/console pimcore:bundle:enable DivanteMagentoIntegrationBundle


Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\RuntimeException: Cannot autowire service "Divante\MagentoIntegrationBundle\Service\Product\ProductStatusService": argument "$mapper" of method "Divante\MagentoIntegrationBundle\Service\AbstractObjectService::__construct()" references interface "Divante\MagentoIntegrationBundle\Interfaces\MapperInterface" but no such service exists. Did you create a class that implements this interface? in /home/nubixpim1/domains/pim.nubix.dev/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/DefinitionErrorExceptionPass.php:54
Stack trace:
#0 /home/nubixpim1/domains/pim.nubix.dev/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(82): Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass->processValue(Object(Symfony\Component\DependencyInjection\Definition), true)
#1 /home/nubixpim1/domains/pim.nubix.dev/public_html/vendor/symfony/symfony/src/Symfony/C in /home/nubixpim1/domains/pim.nubix.dev/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/DefinitionErrorExceptionPass.php on line 54

 // Running bin/console cache:clear...

**Comment by mbolka** [comment]
Can you try to run 
php bin/console pimcore:bundle:enable DivanteObjectMapperBundle first and then 
php bin/console pimcore:bundle:enable DivanteMagentoIntegrationBundle ?

**Comment by supportnubix** [comment]
Thanks mbolka, it worked for us.
