### ISSUE TITLE
Integration-configuration : Magento Store not showing any stores

### ISSUE THREAD

**Issue by srinivastv-github** [DivanteLtd/pimcore-magento2-bridge#33]
hi,
We have installed the plugin in PIMCore 6.3. While configuring the Magento values its not showing the "Stores".

PIMCore : 6.3.1
Magento 2 CE : 2.3 
Please help us

**Comment by mbolka** [comment]
@srinivastv-github Can you send me logs from this process? Maybe it is caused by the configuration of the connector.
