### ISSUE TITLE
If i use select box in pimcore side, am getting Call to a member function getReferencedFields() on boolean

### ISSUE THREAD

**Issue by baladpi** [DivanteLtd/pimcore-magento2-bridge#34]
vendor\/divante-ltd\/pimcore-magento2-bridge\/src\/Divante\/MagentoIntegrationBundle\/Service\/MapperService.php","line":247

**Comment by baladpi** [comment]
am using pimcore 6.3.3

**Comment by mbolka** [comment]
@baladpi Thank you for reporting this issue. We have investigated a potential cause of this issue and resolved it here: https://github.com/DivanteLtd/pimcore-magento2-bridge/pull/35
The newest version 1.2.1 is already implementing it. Could you verify if that solves this issue?

**Comment by baladpi** [comment]
Thank you @mbolka , Its working now.. Now I have a query, that how can i pass the "attribute set id", which is exist in magento side..
For e.g: I created a attribute set named "Food Products" ( attribute is created with id : 19 ) in magento,
Then i pass the attribute from pimcore "attribute_set_id" with the ID 19, but its creating new attribute set in magento like "pimcore-set-27"

**Comment by mbolka** [comment]
PImcore-Magento connector automatically creates attrbiutes sets based on data from Pimcore. It is not possible to manually decide what attribute set should be connected to what product. 
Connector creates a checksum of all attributes in a given product and verifies if this set already exists. If yes, then the existing attribute set is assigned, otherwise, the new one is created.

**Comment by baladpi** [comment]
Thank you.. So what is the use of "Default Classification Store".. I created "Classification Store" in pimcore and I selected the name of the "Classification Store" from the drop down.. But I didn't understand how its working.. Can you please help on " How to use Default Classification Store"

**Comment by mbolka** [comment]
@baladpi You might want to have multiple output channels with unique classification for each of them. So you can use different classification stores for each output channel. 
For ex. Product has 2 fields: classification_1, classification_2
You have 2 classification stores: ETIMv4, ETIMv6
And you want to send only ETIMv4  values to magento_A, and ETIMv6 values to magento_B,
so you define ETIMv4 as a default classification store for magento_A and ETIMv6 for magento_B
