### ISSUE TITLE
IntegrationConfiguration class overwritting existing class during installation

### ISSUE THREAD

**Issue by bgolda** [DivanteLtd/pimcore-magento2-bridge#43]
Hello,

we've managed to install magento bridge successfully on Pimcore v6.4.2, but somehow the IntegrationConfiguration class has overwritten one of already existing classes with ID = 4. I couldn't find any information in the documentation about this case or in existing issues neither. Is this class supposed to have this ID reserved, or is it some kind of a bug during installation? 
Could you please help me fix this issue?

**Comment by mbolka** [comment]
Hi @bgolda!
Thank you for your message. You are right, inside our class definition we have hardcoded ID:4. It should not override your existing class. It is not an expected behavior. We will fix this issue today.

**Comment by mbolka** [comment]
@bgolda Can you confirm that the issue is resolved?

**Comment by bgolda** [comment]
This resolved the issue for now. My suggestion to further improve this solution is to make this class take first ID that is not used yet. Since in the newer  Pimcore versions user is able to define class ID by himself when creating it, there is a possibility that the problem will occur for someone else if the ID is still hardcoded. Thank you for your help and for considering my suggestion.
