### ISSUE TITLE
Question: what is apprx. speed of connector to export 1000 products

### ISSUE THREAD

**Issue by ankit-sf** [DivanteLtd/pimcore-magento2-bridge#5]
Question: what is apprx. speed of this connector to export 1000 products into magento2 from pimcore?

**Comment by mbolka** [comment]
The process is done asynchronously. Pimcore sends an only notification to Magneto, and cron on Magento side can trigger fetich the products from Pimcore. We have tested importing 30 simple products and it has taken around 25 seconds to fetch data, create attributes and attributes sets and save products.
