### ISSUE TITLE
Product/Category Class Templates

### ISSUE THREAD

**Issue by Xcreen** [DivanteLtd/pimcore-magento2-bridge#7]
Hi,
are there templates available on how a product/category class should be look like?
Or do we have todo that manually and check which mappings are availble?

Thank you.

**Comment by marcindyguda** [comment]
hi @Xcreen we will be releasing a tutorial video quite soon, that will be helpful. Stay tuned.

**Comment by mbolka** [comment]
@Xcreen you can find mentioned video here: https://www.youtube.com/watch?v=xuxr4z7H06o

## Product class requirements
### Mandatory

1. Text attribute for product name
2. Unique text / numeric attribute that will be mapped into SKU
3. Unique text attribute that will be used as Url Key.
4. Attribute with type yes/no or selection with values: true, false to determine if product should be enabled
5. Attribute with type with type yes/no or selection to determine if product should be visible in Magento store
6. Many-to-many attribute for storing gallery
7. Many-to-many / many-to-one attribute for storing categories

### Optional

1. Many-to-many attribute for related products
2. Numeric type for quantity
3. Numeric type for price
4. Date type for news from and news to date	
5. Text attribute for description
6. Text attribute for short description
7. Image type attributes for storing main image, small image, thumbnail
8. Many-to-many attribute for storing image gallery

## Category class requirements
### Mandatory
Text attribute that will be mapped into the category name.
Attribute with type yes/no or selection with values: true, false to determine if category should be enabled
### Optional
Text attribute for description.
Image attribute for category image
